trigger:
- main

pool:
  name: Default

schedules:
- cron: "0 6 * * *"
  displayName: Daily 6AM Run
  branches:
    include:
    - main
  always: true

variables:
- group: databricks-variables

steps:

- script: |
    C:\azagent\databricks.exe --version
  displayName: 'Verify Databricks CLI'

- script: |
    C:\azagent\databricks.exe bundle validate
  displayName: 'Validate Bundle'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

- script: |
    C:\azagent\databricks.exe bundle deploy -t dev
  displayName: 'Deploy Bundle to Dev'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

- script: |
    C:\azagent\databricks.exe bundle run medallion_pipeline -t dev
  displayName: 'Run Databricks Workflow'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
